/// Level configurations for the game
/// 
/// Auto-generated by GameFactory.
/// Contains all 10 level configurations with difficulty curve.

class LevelConfig {
  final int levelNumber;
  final String name;
  final bool isFree;
  final String unlockRequirement;
  final double difficulty;
  final int? timeLimitSeconds;
  final int targetScore;
  final int obstacleCount;
  final double obstacleSpeed;
  final int collectibleCount;
  final int collectibleValue;
  final String backgroundTheme;

  const LevelConfig({
    required this.levelNumber,
    required this.name,
    required this.isFree,
    required this.unlockRequirement,
    required this.difficulty,
    this.timeLimitSeconds,
    required this.targetScore,
    required this.obstacleCount,
    required this.obstacleSpeed,
    required this.collectibleCount,
    required this.collectibleValue,
    required this.backgroundTheme,
  });
}

class LevelConfigs {
  LevelConfigs._();

  static const List<LevelConfig> levels = [
    LevelConfig(
      levelNumber: 1,
      name: 'Easy Start',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.1,
      timeLimitSeconds: 60,
      targetScore: 500,
      obstacleCount: 3,
      obstacleSpeed: 0,
      collectibleCount: 10,
      collectibleValue: 10,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 2,
      name: 'Jumping Practice',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.2,
      timeLimitSeconds: 60,
      targetScore: 750,
      obstacleCount: 5,
      obstacleSpeed: 0,
      collectibleCount: 15,
      collectibleValue: 10,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 3,
      name: 'Obstacle Course',
      isFree: true,
      unlockRequirement: 'none',
      difficulty: 0.3,
      timeLimitSeconds: 90,
      targetScore: 1000,
      obstacleCount: 7,
      obstacleSpeed: 0,
      collectibleCount: 20,
      collectibleValue: 10,
      backgroundTheme: 'grassy_meadow',
    ),
    LevelConfig(
      levelNumber: 4,
      name: 'Moving Platforms',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.4,
      timeLimitSeconds: 90,
      targetScore: 1500,
      obstacleCount: 5,
      obstacleSpeed: 2,
      collectibleCount: 25,
      collectibleValue: 10,
      backgroundTheme: 'city_rooftops',
    ),
    LevelConfig(
      levelNumber: 5,
      name: 'Precision Jumps',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.5,
      timeLimitSeconds: 120,
      targetScore: 2000,
      obstacleCount: 7,
      obstacleSpeed: 3,
      collectibleCount: 10,
      collectibleValue: 50,
      backgroundTheme: 'city_rooftops',
    ),
    LevelConfig(
      levelNumber: 6,
      name: 'Tricky Timing',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.6,
      timeLimitSeconds: 120,
      targetScore: 2500,
      obstacleCount: 10,
      obstacleSpeed: 4,
      collectibleCount: 12,
      collectibleValue: 50,
      backgroundTheme: 'industrial_factory',
    ),
    LevelConfig(
      levelNumber: 7,
      name: 'Gauntlet',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.7,
      timeLimitSeconds: 150,
      targetScore: 3000,
      obstacleCount: 12,
      obstacleSpeed: 5,
      collectibleCount: 15,
      collectibleValue: 50,
      backgroundTheme: 'industrial_factory',
    ),
    LevelConfig(
      levelNumber: 8,
      name: 'Challenging Sequence',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.8,
      timeLimitSeconds: 150,
      targetScore: 3500,
      obstacleCount: 15,
      obstacleSpeed: 6,
      collectibleCount: 18,
      collectibleValue: 50,
      backgroundTheme: 'futuristic_city',
    ),
    LevelConfig(
      levelNumber: 9,
      name: 'Precision Madness',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 0.9,
      timeLimitSeconds: 180,
      targetScore: 4000,
      obstacleCount: 18,
      obstacleSpeed: 7,
      collectibleCount: 20,
      collectibleValue: 50,
      backgroundTheme: 'futuristic_city',
    ),
    LevelConfig(
      levelNumber: 10,
      name: 'Extreme Challenge',
      isFree: false,
      unlockRequirement: 'rewarded_ad',
      difficulty: 1.0,
      timeLimitSeconds: 180,
      targetScore: 5000,
      obstacleCount: 20,
      obstacleSpeed: 8,
      collectibleCount: 25,
      collectibleValue: 50,
      backgroundTheme: 'futuristic_city',
    ),
  ];

  static LevelConfig getLevel(int level) {
    if (level < 1 || level > levels.length) {
      return levels.first;
    }
    return levels[level - 1];
  }

  static bool isLevelFree(int level) {
    if (level < 1 || level > levels.length) return false;
    return levels[level - 1].isFree;
  }

  static int get totalLevels => levels.length;
  static int get freeLevels => levels.where((l) => l.isFree).length;
}
